print md to screen if path is NULL
ropensci/tinkr pull request #34
Opened 2020-11-05 08:12 UTC by maelle

Or maybe just head and tail... depending on a parameter?

2020-11-05 18:13 UTC, zkamvar commented
> Or maybe just head and tail... depending on a parameter?

I would prefer to continue to have the `$write()` method return the object, invisibly so that it can be used in a chain: `x$add_md("# title",)$write("file.md")$reset()`

2020-11-05 18:33 UTC, zkamvar requested changes
> Or maybe just head and tail... depending on a parameter?

I would prefer to continue to have the `$write()` method return the object, invisibly so that it can be used in a chain: 

```r
x$add_md("# title")$write("file.md")$reset()
```

I think the methods should be semantically concise and avoid the need for several arguments, so having `$write()` both write a file and output markdown seems to be a bit of misnomer. Instead, I think it would be better to have a `$write()` method and a `$head()` and `$tail()` method.

2020-11-05 18:33 UTC, zkamvar commented on R/class-yarn.R
> -      invisible(self)
This part is important for chaining R6 methods (described in the last paragraph of the "Private Members" section: https://r6.r-lib.org/articles/Introduction.html#private-members)

2020-11-06 15:13 UTC, maelle commented
I'm a bit lost, what do I need to change?

2020-11-06 16:57 UTC, zkamvar commented
Closing this because we came to a consensus that having `head()`, `tail()` and `show()` methods would be better.

2020-11-06 16:57 UTC, closed without merging